#!/usr/bin/env bash
set -e

if [[ -z "${JOLOKIA_JAVAAGENT_OPTS}" ]]; then
    JOLOKIA_JAVAAGENT_OPTS="-javaagent:${JAVAAGENT_BIN_DIR}/${JOLOKIA_JAVAAGENT_FILENAME}=port=${JOLOKIA_PORT},host=0.0.0.0"
    if [[ ! -z "${JOLOKIA_DISCOVERY_HOSTNAME_COMMAND}" ]]; then
        JOLOKIA_DISCOVERY_HOSTNAME=$(eval "${JOLOKIA_DISCOVERY_HOSTNAME_COMMAND}")
    fi
    if [[ ! -z "${JOLOKIA_DISCOVERY_HOSTNAME}" ]]; then
        JOLOKIA_JAVAAGENT_OPTS="${JOLOKIA_JAVAAGENT_OPTS},discoveryAgentUrl=http://${JOLOKIA_DISCOVERY_HOSTNAME}:${JOLOKIA_DISCOVERY_PORT:-${JOLOKIA_PORT}}/jolokia"
    fi
    if [[ ! -z "${JOLOKIA_AGENTID_COMMAND}" ]]; then
        JOLOKIA_AGENTID=$(eval "${JOLOKIA_AGENTID_COMMAND}")
    fi
    if [[ ! -z "${JOLOKIA_AGENTID}" ]]; then
        JOLOKIA_JAVAAGENT_OPTS="${JOLOKIA_JAVAAGENT_OPTS},agentId=${JOLOKIA_AGENTID}"
    fi
    export JOLOKIA_JAVAAGENT_OPTS
fi

if [[ -z "${PROMETHEUS_JAVAAGENT_OPTS}" ]]; then
    PROMETHEUS_JAVAAGENT_OPTS="-javaagent:${JAVAAGENT_BIN_DIR}/${PROMETHEUS_JAVAAGENT_FILENAME}=${PROMETHEUS_PORT}:${JAVAAGENT_CONFIG_DIR}/${PROMETHEUS_CONFIG_FILENAME}"
    export PROMETHEUS_JAVAAGENT_OPTS
fi

export KAFKA_OPTS="${KAFKA_OPTS} ${JOLOKIA_JAVAAGENT_OPTS} ${PROMETHEUS_JAVAAGENT_OPTS}"

exec start-kafka.sh